# Generated by Django 6.0.3 on 2026-05-18 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samaj_events', '0002_eventparticipant'),
    ]

    operations = [
        migrations.AddField(
            model_name='secretpoll',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='When the poll automatically closes', null=True),
        ),
    ]
