# Generated by Django 6.0.3 on 2026-05-20 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0001_initial'),
        ('samaj_events', '0004_eventchatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='blooddonationrecord',
            name='guest_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='blooddonationrecord',
            name='guest_age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='samajevent',
            name='event_status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='ACTIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='samajevent',
            name='max_participants',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sportsteam',
            name='team_color',
            field=models.CharField(default='#3B82F6', help_text='Hex color e.g. #3B82F6', max_length=7),
        ),
        migrations.AddField(
            model_name='tournamentplayer',
            name='jersey_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blooddonationrecord',
            name='guest_blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='eventorganizer',
            name='role_title',
            field=models.CharField(choices=[('Event Admin', 'Event Admin'), ('Event Member', 'Event Member')], default='Event Member', max_length=100),
        ),
        migrations.AlterField(
            model_name='pollvote',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pollvote_set', to='samaj_events.polloption'),
        ),
        migrations.AlterField(
            model_name='samajevent',
            name='event_scope',
            field=models.CharField(choices=[('GLOBAL', 'Whole Samaj'), ('DISTRICT', 'District Level'), ('CITY', 'City / Village Level')], default='GLOBAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='samajevent',
            name='target_city_village',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='samajevent',
            name='target_district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='secretpoll',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='secretpoll',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('CLOSED', 'Closed')], default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='sportsteam',
            name='captain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captained_teams', to='core_app.samajprofile'),
        ),
        migrations.AlterField(
            model_name='tournamentplayer',
            name='player_role',
            field=models.CharField(blank=True, choices=[('Batsman', 'Batsman'), ('Bowler', 'Bowler'), ('All-Rounder', 'All-Rounder'), ('Wicket-Keeper', 'Wicket-Keeper')], max_length=50, null=True),
        ),
    ]
