; [pytest]
; # Yahan 'textile_project' ki jagah apne main project folder ka naam likhein agar alag ho
; DJANGO_SETTINGS_MODULE = textile_project.settings
; python_files = tests.py test_*.py *_tests.py

; # Terminal mein output clean aur clear dikhne ke liye
; addopts = -v --nomigrations



[pytest]
DJANGO_SETTINGS_MODULE = textile_project.settings
python_files = tests.py test_*.py *_tests.py
addopts = -v --nomigrations

# 🌟 NAYI LINES (Taki DB name load ho sake):
env_files =
    .env