# Generated by Django 6.0.3 on 2026-05-07 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='samajprofile',
            name='registration_source',
            field=models.CharField(choices=[('SELF', 'Self Registered'), ('BULK', 'Bulk Import by Admin')], default='SELF', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('SUPERADMIN', 'System Owner (IT Admin)'), ('CORE_ADMIN', 'Core Admin (Samaj Leader)'), ('CORE_MEMBER', 'Core Member (Verifier)'), ('EVENT_ADMIN', 'Event Manager'), ('USER', 'Standard User'), ('STAFF', 'ERP Staff')], default='USER', max_length=20),
        ),
    ]
