# Generated by Django 6.0.3 on 2026-05-23 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='samajprofile',
            name='blood_group',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='samajprofile',
            name='employment_type',
            field=models.CharField(choices=[('GOVT', 'Government Job'), ('PRIVATE', 'Private Job'), ('BUSINESS', 'Business / Entrepreneur'), ('SELF', 'Self Employed / Professional'), ('OTHER', 'Other / Retired / Student')], default='OTHER', max_length=20),
        ),
        migrations.AddField(
            model_name='samajprofile',
            name='extra_details',
            field=models.JSONField(blank=True, default=dict, help_text='Store unlimited custom attributes like Hobbies, Social Links, etc.'),
        ),
        migrations.AddField(
            model_name='samajprofile',
            name='work_address',
            field=models.TextField(blank=True, help_text='Office or Shop Address', null=True),
        ),
        migrations.AlterField(
            model_name='samajprofile',
            name='business_name',
            field=models.CharField(blank=True, help_text='Company or Business Name', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='samajprofile',
            name='occupation_en',
            field=models.CharField(blank=True, help_text='Designation or Profession', max_length=255, null=True),
        ),
    ]
