# Generated by Django 6.0.3 on 2026-05-01 10:32

import core_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='aadhaar_no',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[core_app.validators.validate_aadhaar_number]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[core_app.validators.validate_mobile_number]),
        ),
    ]
