# Generated by Django 6.0.3 on 2026-05-23 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0002_samajprofile_blood_group_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gotra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=100, unique=True)),
                ('name_hi', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
