# Generated by Django 6.0.3 on 2026-05-08 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0002_samajprofile_registration_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('SUPERADMIN', 'Super Admin (Frontend Boss)'), ('ADMIN', 'Admin (Manager)'), ('CORE_MEMBER', 'Core Member (Verifier)'), ('EVENT_ADMIN', 'Event Admin'), ('EVENT_USER', 'Event User'), ('USER', 'Simple User'), ('STAFF', 'ERP Staff')], default='USER', max_length=20),
        ),
    ]
