# Generated by Django 6.0.3 on 2026-05-27 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0003_gotra'),
    ]

    operations = [
        migrations.AddField(
            model_name='samajprofile',
            name='death_date',
            field=models.DateField(blank=True, help_text='Date of death (if not alive)', null=True),
        ),
        migrations.AddField(
            model_name='samajprofile',
            name='death_reason',
            field=models.CharField(blank=True, help_text='Brief reason or cause of death (optional)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='samajprofile',
            name='marital_status',
            field=models.CharField(choices=[('UNMARRIED', 'Unmarried / अविवाहित'), ('MARRIED', 'Married / विवाहित'), ('WIDOWER', 'Widower / विधुर'), ('WIDOW', 'Widow / विधवा'), ('DIVORCED', 'Divorced / तलाकशुदा'), ('SEPARATED', 'Separated / अलग'), ('REMARRIED', 'Remarried / पुनर्विवाहित')], default='UNMARRIED', help_text='Current marital status — important for matrimonial matching', max_length=20),
        ),
        migrations.AddField(
            model_name='samajprofile',
            name='marriage_date',
            field=models.DateField(blank=True, help_text='Marriage date (for anniversary reminders)', null=True),
        ),
    ]
