# Generated by Django 6.0.3 on 2026-05-04 11:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0003_activitytag_customuser_first_name_hi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='samajprofile',
            name='is_core_member',
            field=models.BooleanField(default=False, help_text='Can verify other pending members'),
        ),
        migrations.CreateModel(
            name='VerificationVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('core_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes_given', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('pending_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes_received', to='core_app.samajprofile')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('core_member', 'pending_profile'), name='unique_verification_vote')],
            },
        ),
    ]
