# Generated by Django 6.0.3 on 2026-05-08 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0003_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('SUPERADMIN', 'System Owner (IT Admin)'), ('ADMIN', 'Admin'), ('CORE_ADMIN', 'Core Admin (Samaj Leader)'), ('CORE_MEMBER', 'Core Member (Verifier)'), ('EVENT_ADMIN', 'Event Admin'), ('EVENT_USER', 'Event User'), ('USER', 'Simple User'), ('STAFF', 'ERP Staff')], default='USER', max_length=20),
        ),
    ]
