# Generated by Django 6.0.3 on 2026-05-10 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0004_alter_customuser_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='samajprofile',
            name='spouse',
        ),
        migrations.AddField(
            model_name='samajprofile',
            name='spouses',
            field=models.ManyToManyField(blank=True, to='core_app.samajprofile'),
        ),
    ]
