# Generated by Django 6.0.3 on 2026-05-30 06:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0004_samajprofile_death_date_samajprofile_death_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samajprofile',
            name='blood_group',
            field=models.CharField(blank=True, db_index=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='samajprofile',
            name='business_name',
            field=models.CharField(blank=True, db_index=True, help_text='Company or Business Name', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='samajprofile',
            name='dob',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='samajprofile',
            name='employment_type',
            field=models.CharField(choices=[('GOVT', 'Government Job'), ('PRIVATE', 'Private Job'), ('BUSINESS', 'Business / Entrepreneur'), ('SELF', 'Self Employed / Professional'), ('OTHER', 'Other / Retired / Student')], db_index=True, default='OTHER', max_length=20),
        ),
        migrations.AlterField(
            model_name='samajprofile',
            name='gotra_en',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='samajprofile',
            name='is_alive',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='samajprofile',
            name='marital_status',
            field=models.CharField(choices=[('UNMARRIED', 'Unmarried / अविवाहित'), ('MARRIED', 'Married / विवाहित'), ('WIDOW_WIDOWER', 'Widow/Widower / विधवा/विधुर'), ('DIVORCED', 'Divorced / तलाकशुदा'), ('SEPARATED', 'Separated / अलग'), ('REMARRIED', 'Remarried / पुनर्विवाहित')], db_index=True, default='UNMARRIED', help_text='Current marital status — important for matrimonial matching', max_length=20),
        ),
        migrations.AlterField(
            model_name='samajprofile',
            name='verification_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='samajprofile',
            name='village_en',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='SamajAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('is_important', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
