# Generated by Django 6.0.3 on 2026-05-30 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0005_alter_samajprofile_blood_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='samajannouncement',
            name='document',
            field=models.FileField(blank=True, help_text='Upload PDFs like Samaj magazines or rulebooks', null=True, upload_to='announcements/docs/'),
        ),
        migrations.AddField(
            model_name='samajannouncement',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload invitation cards or event photos', null=True, upload_to='announcements/images/'),
        ),
    ]
